version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    networks:
      - internalNetwork
  
  imageRecorder:
    image: smb5d/security-camera-image-recorder:latest
    environment:
      - RTSP=null
      - FPS=1
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_QUEUE_NAME=CameraImages
      - ROUTING_KEY=CameraImages
      - CAMERA_NAME=FrontDoor
    restart: unless-stopped
    networks:
      - internalNetwork
  
networks:
  internalNetwork: