version: '3.8'
services:
  imageRecorder:
    image: smb5d/security-camera-image-recorder:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 150M
    restart: unless-stopped
    environment:
      - RTSP=rtsp://rtspserver:8554/stream
      - FPS=0.25
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_QUEUE_NAME=CameraImages
      - CAMERA_NAME=FrontDoorTest
      - ROUTING_KEY=CameraImages
    volumes:
      - type: tmpfs
        target: /images
        tmpfs:
          size: 50m
    networks:
      - common-network
    depends_on:
      cameraemulator:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    
  videoRecoder:
    image: smb5d/security-camera-recorder:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 150M
    restart: unless-stopped
    environment:
      - RTSP=rtsp://rtspserver:8554/stream
      - SEG_TIME=60
      - S3_BUCKET=[your bucket here]
      - S3_DIRECTORY=FrontDoorTest
      - SYNC_S3_AFTER_SECONDS=60
      - UPLOAD_FILE_OLDER_MIN=+1
      - RECORDING_DIRECTORY=/recordings
      - UPLOAD_DIRECTORY=/recordings/upload
      - STORAGE_CLASS=STANDARD
    volumes:
      - type: tmpfs
        target: /recordings
        tmpfs:
          size: 200m 
      - ./credentials:/root/.aws/credentials:ro
    depends_on:
      cameraemulator:
        condition: service_started
    networks:
      - common-network

  cameraemulator:
    build:
      context: .
      dockerfile: dockerfile-camera-simulator
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 150M
    environment:
      - RTSP_URL=rtsp://rtspserver:8554/stream
    depends_on:
      rtspserver:
        condition: service_started
    networks:
      - common-network

  rtspserver:
    image: bluenviron/mediamtx:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 150M
    networks:
      - common-network

  rabbitmq:
    image: rabbitmq:3.12-management
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 300M
        reservations:
          cpus: '0.1'
          memory: 150M
    ports:
      # - 5672:5672
      - 15672:15672
    restart: unless-stopped
    networks:
      - common-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3


networks:
  common-network:
    
          