FROM smb5d/security-camera-recorder:latest

WORKDIR /scripts
COPY Run.sh Run.sh
RUN chmod +x Run.sh
COPY record.sh record.sh
RUN chmod +x record.sh
COPY stores3.sh stores3.sh
RUN chmod +x stores3.sh
COPY rename.sh rename.sh
RUN chmod +x rename.sh

WORKDIR /recordings
ENTRYPOINT [ "/scripts/Run.sh" ] 