name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Go to Recorder directory
      run: cd Recorder
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag smb5d/security-camera-recorder:$(date +%s)
