FROM python:3.11.9-slim-bookworm

RUN apt update 

RUN apt install gcc libgl1 libglib2.0-0 libsm6 libxrender1 libxext6 curl bash -y

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

RUN pip3 install ultralytics