# Use the official image as a parent image.
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim AS build-env
ARG TARGETARCH

# Set the working directory.
WORKDIR /src

# Copy the rest of the working directory contents.
COPY ../ ./

# Build the app.
WORKDIR /src/SecurityCamera.Console.ImageObjectDetection
RUN dotnet publish -a $TARGETARCH -c Release --self-contained true -o /build

# Build runtime image.
FROM python:3.11.9-slim-bookworm

RUN apt update 

RUN apt install gcc libgl1 libglib2.0-0 libsm6 libxrender1 libxext6 curl bash -y

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

RUN pip3 install ultralytics

WORKDIR /app
COPY --from=build-env /build .

WORKDIR /scripts
COPY ../SecurityCamera.Console.ImageObjectDetection/DockerAssets/Run.sh Run.sh
RUN chmod +x Run.sh

WORKDIR /images
# Set the command to run when the container starts.
ENTRYPOINT ["/scripts/Run.sh" ]
