# Use the official image as a parent image.
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim AS build-env
ARG TARGETARCH

# Set the working directory.
WORKDIR /src

# Copy the rest of the working directory contents.
COPY ../ ./

# Build the app.
WORKDIR /src/SecurityCamera.Console.ImageObjectDetection
RUN dotnet publish -a $TARGETARCH -c Release --self-contained true -o /build

FROM python:3.9.19-slim-bookworm

RUN apt update

RUN apt install -y libglib2.0-0 libgl1-mesa-glx libusb-1.0-0 curl

WORKDIR /tflite
COPY --from=build-env /src/SecurityCamera.Infrastructure.TensorflowLite.ObjectDetection/TF_Files .

RUN /tflite/setup.sh

WORKDIR /app
COPY --from=build-env /build .

WORKDIR /scripts
COPY ../SecurityCamera.Console.ImageObjectDetection/DockerAssets/Run.sh Run.sh
RUN chmod +x Run.sh

WORKDIR /images
# Set the command to run when the container starts.
ENTRYPOINT ["/scripts/Run.sh" ]
